/src
  /handlers
    orderHandler.js
    adminHandler.js
    cartHandler.js
    productHandler.js
    startHandler.js
  /middlewares
    authMiddleware.js
    cartMiddleware.js
  /services
    notificationService.js
  /models
    index.js
  bot.js
  server.js
